name: PHP Composer

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Display PHP version
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run style linter
      run: composer run-script style-lint

    - name: Run static analyzer
      run: composer run-script stan

    - name: Run test suite
      run: composer run-script test-ci
